#itemmenu_informe_iglesia
#itemmenu_informe_distrito
#itemmenu_informe_distrito_lider
#itemmenu_informe_zona
itemmenu_informe_campo
itemmenu_informe_union

#menu_imprimir_reporte_iglesia
#menu_imprimir_reporte_distrito
#menu_imprimir_reporte_lider_distrito
#menu_imprimir_reporte_lider_cero
#menu_imprimir_reporte_zona
menu_imprimir_reporte_campo
menu_imprimir_reporte_lider_destacado
menu_imprimir_reporte_union
